### ISSUE TITLE
Lots of clipping since 5.0

### ISSUE THREAD

**Issue by BullOnMars** [Animal42069/BetterPenetration#23]
Clipping getting worse in 5.0 especially in the belly area, part of the belly clips through tight clothing during animation like MMD dance even nothing related to BP is happening.

**Comment by roy12-meh** [comment]
One way to fix it is disabling belly bulging entirely in the settings, though that still seems to cause the dynamic bones to bounce, still causing clipping.

I'm copy pasting what I wrote in Patreon so it doesn't get lost there.

It's possible to use bone implantor to add the belly bones to clothes, and copying the Dynamic Bone from BP uncensors has it working. It comes with some problems though. If all uncensors don't have the same belly Dynamic Bone settings, it will desync. The radius for the clothes belly Dynamic Bone needs to be set to 0, otherwise they clip with the cf_hit_Kosi02_s vanilla collider. With all these workarounds, whenever BP causes belly bulging, it's back to clipping with the body. While using a clipping mask could be a workaround, this doesn't work for anything with transparency.

A solution could be having BP detecting the bones in the clothes and syncing them with the uncensor bones instances? That way they would both be affected by the same bones and same dynamic bone settings. This doesn't take pussy bones in account though, which I think can differ between uncensors?

One example where you can see the issue is with the Latex Catsuit (should be available in the repack I think) which has transparency control. It also depends on the thickness of your girl.

**Comment by BullOnMars** [comment]
Disabling bulging doesn't fully fix the clipping, I guess the weighting for BP5 body in the particular area is different from vanilla body, since most tight and thin clothing is made with vanilla body weighting.
